export const REQUEST_NETWORKS_SUCCESS = 'BIKES/REQUEST_NETWORKS_SUCCESS';
export const REQUEST_NETWORKS = 'BIKES/REQUEST_NETWORKS';
export const CHANGE_IS_NETWORKS_PRELOADING = 'BIKES/CHANGE_IS_NETWORKS_PRELOADING';

export const REQUEST_STATIONS_SUCCESS = 'BIKES/REQUEST_STATIONS_SUCCESS';
export const REQUEST_STATIONS = 'BIKES/REQUEST_STATIONS';
export const CHANGE_IS_STATIONS_PRELOADING = 'BIKES/CHANGE_IS_STATIONS_PRELOADING';

export const REQUEST_SELECTED_BIKE = 'BIKES/REQUEST_SELECTED_BIKE';
export const SET_NETWORK_ID = 'BIKES/SET_NETWORK_ID';
